output_dir: "synthetic_dataset"
log_level: "INFO"

transformations:
  rotation_range: [-180, 180]
  translation_range: [-30, 30]
  variants_per_image: 5
  min_dof_modified: 1
  max_dof_modified: 6

dataset:
  extensions: [".nii", ".nii.gz"]
  batch_size: 10
  validate_outputs: true

sample:
  enabled: true
  dimensions: [128, 128, 64]
  voxel_size: [1.0, 1.0, 1.0]
  add_noise: true
  noise_level: 0.1 