model:
  input_size: [96, 96, 48]
  dropout_rate: 0.2

training:
  batch_size: 2
  num_epochs: 30
  learning_rate: 0.0002
  weight_decay: 0.00001
  val_split: 0.2
  num_workers: 0
  log_interval: 10
  log_dir: "runs/dof_regression_improved"
  checkpoint_dir: "checkpoints"
  early_stopping:
    enabled: true
    patience: 10

data:
  metadata_dir: "synthetic_training_data"
  target_size: [96, 96, 48] 