dataset:
  batch_size: 5
  extensions:
  - .nii
  - .nii.gz
  validate_outputs: true
log_level: INFO
output_dir: synthetic_training_data
sample:
  add_noise: false
  dimensions:
  - 128
  - 128
  - 64
  enabled: false
  noise_level: 0.05
  voxel_size:
  - 1.0
  - 1.0
  - 1.0
transformations:
  max_dof_modified: 3
  min_dof_modified: 1
  rotation_range:
  - -45
  - 45
  translation_range:
  - -20
  - 20
  variants_per_image: 50
